[tool.ruff]
target-version = "py313"
required-version = ">=0.9.7"
line-length = 120
src = ["src"]
fix = true

[tool.ruff.lint]
# only ignore variables named "_"
dummy-variable-rgx = "^_$"
select = [
    "A",      # flake8-builtins
    "B",      # flake8-bugbear
    "E",      # pycodestyle
    "F",      # pyflakes
    "G",      # flake8-logging-format
    "I",      # isort
    "Q",      # flake8-quotes
    "R",      # flake8-return
    "S",      # flake8-bandit
    "W",      # pycodestyle
    "ASYNC",  # flake8-async
    "FAST",   # fastapi
    "LOG",    # flake8-logging
    "SIM",    # flake8-simplify
    "ANN202", # flake8-annotations
    "ANN205", # flake8-annotations
    "ANN206", # flake8-annotations
    "COM812", # flake8-commas
    "COM818", # flake8-commas
    "D204",   # pydocstyle
]
ignore = [
    "B008", # flake8-bugbear
    "S321", # flake8-bandit
]
fixable = [
    "F401", # pyflakes
]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
suppress-none-returning = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "standard"